### ISSUE TITLE
Pytorch nightly build failing

### ISSUE THREAD

**Issue by darren-pei** [facebookresearch/fairscale#1057]
Hi

I'm trying to get detectron2 working on my Macos M1 with mps, I'm using the pytorch nightly build, but I'm getting the following error:

`Traceback (most recent call last):
  File "/Users/darrenthorpe/PycharmProjects/tableDetection/scripts/detectron.py", line 5, in <module>
    from detectron2 import model_zoo
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/model_zoo/__init__.py", line 8, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url, get_config
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/model_zoo/model_zoo.py", line 9, in <module>
    from detectron2.modeling import build_model
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/__init__.py", line 5, in <module>
    from .backbone import (
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/backbone/__init__.py", line 15, in <module>
    from .vit import ViT, SimpleFeaturePyramid, get_vit_lr_decay_rate
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/backbone/vit.py", line 10, in <module>
    from fairscale.nn.checkpoint import checkpoint_wrapper
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 38, in <module>
    from torch.distributed import ProcessGroup
ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' (/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/torch/distributed/__init__.py)
`

Is there a compatible nightly build for fairscale?

Thanks

Darren

**Comment by min-xu-ai** [comment]
Thanks for the report! Looks like ProcessGroup is moved or something. @anupambhatnagar @ruanslv, do you guys have time to look into this?

**Comment by anupambhatnagar** [comment]
@darren-pei can you provide steps to reproduce this? exact versions of the libraries being used would be helpful.

**Comment by darren-pei** [comment]
Here you go, pretty easy to replicate:

`from detectron2.engine import DefaultTrainer
x = 1`

Produces error:

```
Traceback (most recent call last):
  File "/Users/darrenthorpe/PycharmProjects/tableDetection/scripts/bug_report.py", line 1, in <module>
    from detectron2.engine import DefaultTrainer
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/engine/__init__.py", line 12, in <module>
    from .defaults import *
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 38, in <module>
    from detectron2.modeling import build_model
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/__init__.py", line 5, in <module>
    from .backbone import (
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/backbone/__init__.py", line 15, in <module>
    from .vit import ViT, SimpleFeaturePyramid, get_vit_lr_decay_rate
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/detectron2/modeling/backbone/vit.py", line 10, in <module>
    from fairscale.nn.checkpoint import checkpoint_wrapper
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 38, in <module>
    from torch.distributed import ProcessGroup
ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' (/Users/darrenthorpe/miniforge3/envs/torch-gpu-3.9/lib/python3.9/site-packages/torch/distributed/__init__.py)

Process finished with exit code 1
```

Installed packages:

```# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
aom                       3.4.0                hbe31e94_1    conda-forge
black                     22.3.0                   pypi_0    pypi
brotlipy                  0.7.0           py39hb18efdd_1004    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15        py39h2804cbe_0    conda-forge
cffi                      1.15.1           py39h04d3946_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
cryptography              37.0.4           py39h4cb6239_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
detectron2                0.6                      pypi_0    pypi
expat                     2.4.8                h6b3803e_0    conda-forge
fairscale                 0.4.8                    pypi_0    pypi
ffmpeg                    4.4.2           gpl_h0b00469_106    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hfb34624_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4                   pypi_0    pypi
freetype                  2.10.4               h17b34a0_1    conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.7.6                h27a1928_5    conda-forge
google-auth               2.10.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
icu                       70.1                 h6b3803e_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.12.0                   pypi_0    pypi
iopath                    0.1.9                    pypi_0    pypi
jpeg                      9e                   he4db4b2_2    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h27ca646_1001    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           15_osxarm64_openblas    conda-forge
libcblas                  3.9.0           15_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libdeflate                1.13                 h57fd34a_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libidn2                   2.3.3                he4db4b2_0    conda-forge
liblapack                 3.9.0           15_osxarm64_openblas    conda-forge
libopenblas               0.3.20          openmp_h130de29_1    conda-forge
libpng                    1.6.37               h2c9beb0_3    conda-forge
libprotobuf               3.20.1               h332123e_0    conda-forge
libtasn1                  4.18.0               he4db4b2_1    conda-forge
libtiff                   4.4.0                hd6ca8d7_3    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libvpx                    1.11.0               hc470f4d_3    conda-forge
libwebp                   1.2.3                h1e26fe3_1    conda-forge
libwebp-base              1.2.3                he4db4b2_2    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.9.14               h035c1df_3    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.3                  h07bb92c_1    conda-forge
nettle                    3.8.1                h63371fa_1    conda-forge
ninja                     1.11.0               hf86a087_0    conda-forge
numpy                     1.23.1           py39h7df2422_0    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.2.2                    pypi_0    pypi
openh264                  2.2.0                h9a09cb3_2    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   1.1.1q               ha287fd2_0    conda-forge
p11-kit                   0.24.1               h29577a5_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pillow                    9.2.0            py39h1b8be2f_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
portalocker               2.5.1                    pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               h27ca646_1001    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.4                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydot                     1.4.2                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h2804cbe_5    conda-forge
python                    3.9.13          hc596b02_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.0          cpu_py39h0768760_2    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
setuptools                63.4.2           py39h2804cbe_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sleef                     3.5.1                h156473d_2    conda-forge
sqlite                    3.39.2               h40dfcc0_0    conda-forge
svt-av1                   1.1.0                hbe31e94_1    conda-forge
tabulate                  0.8.10                   pypi_0    pypi
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
timm                      0.6.7                    pypi_0    pypi
tk                        8.6.12               he1e0b03_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.12.0                 py39_cpu    pytorch
torchvision               0.13.0          cpu_py39h80956b8_0    conda-forge
tqdm                      4.64.0                   pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h3422bc3_1    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               ha287fd2_2    conda-forge
zstd                      1.5.2                hd705a24_2    conda-forge```

Packages installed with:

```conda install pytorch torchvision torchaudio -c pytorch-nightly
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```

OS Version:  macOS Monterey 12.5 Apple M1 chip

Thanks

Darren

**Comment by anupambhatnagar** [comment]
As the last line of the error message indicates, this error is not from fairscale but pytorch distributed. Please make sure you can import ProcessGroup in your environment. I suggest trying the import statement in a python repl in the same conda environment.

**Comment by min-xu-ai** [comment]
> As the last line of the error message indicates, this error is not from fairscale but pytorch distributed. Please make sure you can import ProcessGroup in your environment. I suggest trying the import statement in a python repl in the same conda environment.

Maybe in newer version of pytorch ProcessGroup is moved? In that case, FSDP code should be updated to import it from the new module it moved into?

**Comment by darren-pei** [comment]
> As the last line of the error message indicates, this error is not from fairscale but pytorch distributed. Please make sure you can import ProcessGroup in your environment. I suggest trying the import statement in a python repl in the same conda environment.

Fair point, we'll made 😀

**Comment by ppwwyyxx** [comment]
I believe this is a problem of fairscale. According to pytorch code:
https://github.com/pytorch/pytorch/blob/735ab791684581cd800da2807a635b1f486f8a67/torch/distributed/__init__.py#L24-L29

`ProcessGroup` is available only if `torch.distributed.is_available()` is True.

In other words, fairscale should not import `ProcessGroup` unconditionally - this makes fairscale un-importable on any machine where `torch.distributed.is_available()==False`.

If fairscale decides to import ProcessGroup unconditionally, then fairscale users will have to do the extra work to conditionally import fairscale.

**Comment by min-xu-ai** [comment]
@ppwwyyxx Thanks so much Yuxin! This explains it! I will make a fix.
