### ISSUE TITLE
How to use Pipe in evaluation mode

### ISSUE THREAD

**Issue by SeanNaren** [facebookresearch/fairscale#173]
## ❓ Questions and Help

Was curious if the Pipe module can be used in evaluation mode... I have a script which is just the modified `benchmark/pipe.py` but stripped down/self-contained and runs the `evaluate` function.

https://gist.github.com/SeanNaren/6a91ad9c5d82bf7e6ccb3081ff086067

Running this. gives me an error in evaluate (I have to run it twice, once to download the data then crashes/then once properly):

```
~/fairscale$ python benchmarks/pipe.py  --num-decoder-layers 4 --chunks 1 --pipelined-backward
dist init r=0, world=2, host=localhost
dist init r=1, world=2, host=localhost
> initializing model parallel with size 1
--------------------------------------------------------------------------------------------------------------
| start of epoch 1
--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
| start of epoch 1
--------------------------------------------------------------------------------------------------------------
[E thread_pool.cpp:112] Exception in thread pool task: TypeError: 'NoneType' object is not callable
[W tensorpipe_agent.cpp:545] RPC agent for Test1 encountered error when reading incoming request from Test0: EOF: end of file (this is expected to happen during shutdown)
Traceback (most recent call last):
  File "benchmarks/pipe.py", line 512, in <module>
    bench_multi_process(args, all_at_once=True)
  File "benchmarks/pipe.py", line 481, in bench_multi_process
    mp.spawn(run_worker, args=(world_size, args), nprocs=world_size, join=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jovyan/fairscale/benchmarks/pipe.py", line 470, in run_worker
    run_mp_worker(args, world_size)
  File "/home/jovyan/fairscale/benchmarks/pipe.py", line 461, in run_mp_worker
    args)
  File "/home/jovyan/fairscale/benchmarks/pipe.py", line 348, in benchmark_language_model
    val_loss = evaluate(model, val_data, criterion, bptt, ntokens)
  File "/home/jovyan/fairscale/benchmarks/pipe.py", line 328, in evaluate
    output = output.to(targets.device)
AttributeError: 'list' object has no attribute 'to'
```
cmd:
```
python benchmarks/pipe.py  --num-decoder-layers 4 --chunks 1
```
From investigating on 2 GPU machine with the above cmd, rank 0 returns a `Batch` object, and rank 1 returns a tensor. Is there a way for these to be synced? I assume rank 0 contains just the output for the layers on rank 0, however i'm wondering what the flow should be for evaluation.

The goal is to prototype single-process single-device Pipe parallelism + data parallel for pytorch lightning (for extra info!). Any thoughts here would be appreciated as well :)

**Comment by froody** [comment]
@SeanNaren sorry for the lack of documentation, in with PipelineStyle.MultiProcess, only the final stage receives the output, so you need to rewrite your [code](https://gist.github.com/SeanNaren/6a91ad9c5d82bf7e6ccb3081ff086067#file-benchmark_pipe-py-L328-L330) as:
```
if eval_model.final_stage:
    output = output.to(targets.device)
    output_flat = output.view(-1, ntokens)
    total_loss += len(data) * criterion(output_flat, targets).item()
```

I am working on an update which controls all stages of the pipeline from a single process via torch.distributed.rpc, so that will make this unnecessary in the future.

**Comment by SeanNaren** [comment]
@froody thanks for your response! Might be better to wait for this update, is this the PR to track? https://github.com/facebookresearch/fairscale/pull/156

**Comment by froody** [comment]
Yes #156  is the right PR
