### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by pclucas14** [facebookresearch/fairscale#478]
Hi, 

I am trying to install fairscale using pip. I am running a fresh python 3.7 environment. I keep running into this issue 
 ```
ERROR: Could not build wheels for fairscale which use PEP 517 and cannot be installed directly
```

which seems `pip` related. I have ugraded my pip to the most recent version, and still the error persists. `pip -V` returns version `20.0.1`

**Comment by blefaudeux** [comment]
Hi, thanks for reporting the issue ! Could that be missing setuptools and  wheel ? Would you mind trying `pip install setuptools wheel` ?

**Comment by pclucas14** [comment]
It seems the packages are already installed 

```
(fairscale) lucaspc@devfair0224:~/repos/my_vissl$ pip install setuptools wheel
Looking in indexes: https://pypi.org/simple, http://webservice
Requirement already satisfied: setuptools in /private/home/lucaspc/.conda/envs/fairscale/lib/python3.7/site-packages (49.6.0.post20210108)
Requirement already satisfied: wheel in /private/home/lucaspc/.conda/envs/fairscale/lib/python3.7/site-packages (0.36.2)
(fairscale) lucaspc@devfair0224:~/repos/my_vissl$
```

**Comment by min-xu-ai** [comment]
Can you try some commands in #264 to see if they workaround your problem? @pclucas14 

Worst case, you can git clone the repo and install with `pip install -e .`?

**Comment by pclucas14** [comment]
Neither `pip install fairscale -v --no-cache` nor `pip install fairscale --no-build-isolation` worked (the latter giving the same error). I also tried building from scratch, and got the following error (on the `pip install -e .` step)

```
Installing collected packages: fairscale
  Running setup.py develop for fairscale
    ERROR: Command errored out with exit status 1:
     command: /private/home/lucaspc/.conda/envs/vissl/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/home/lucaspc/repos/fairscale/setup.py'"'"'; __file__='"'"'/private/home/lucaspc/repos/fairscale/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /private/home/lucaspc/repos/fairscale/
    Complete output (85 lines):
    running develop
    running egg_info
    writing fairscale.egg-info/PKG-INFO
    writing dependency_links to fairscale.egg-info/dependency_links.txt
    writing requirements to fairscale.egg-info/requires.txt
    writing top-level names to fairscale.egg-info/top_level.txt
    reading manifest file 'fairscale.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fairscale.egg-info/SOURCES.txt'
    running build_ext
    building 'fairscale.fused_adam_cuda' extension
    Emitting ninja build file /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/dist.py:636: UserWarning: Usage of dash-separated 'max-line-length' will not be supported in future versions. Please use the underscore name 'max_line_length' instead
      % (opt, underscore_opt))
    /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/dist.py:636: UserWarning: Usage of dash-separated 'per-file-ignores' will not be supported in future versions. Please use the underscore name 'per_file_ignores' instead
      % (opt, underscore_opt))
    [1/2] /public/apps/cuda/10.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.o.d -I/private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/THC -I/public/apps/cuda/10.1/include -I/private/home/lucaspc/.conda/envs/vissl/include/python3.7m -c -c /private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu -o /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fused_adam_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_60,code=sm_60 -std=c++14
    FAILED: /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.o
    /public/apps/cuda/10.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.o.d -I/private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/THC -I/public/apps/cuda/10.1/include -I/private/home/lucaspc/.conda/envs/vissl/include/python3.7m -c -c /private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.cu -o /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fused_adam_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_60,code=sm_60 -std=c++14
    nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
    [2/2] c++ -MMD -MF /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda.o.d -pthread -B /private/home/lucaspc/.conda/envs/vissl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/THC -I/public/apps/cuda/10.1/include -I/private/home/lucaspc/.conda/envs/vissl/include/python3.7m -c -c /private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda/fused_adam_cuda.cpp -o /private/home/lucaspc/repos/fairscale/build/temp.linux-x86_64-3.7/fairscale/clib/fused_adam_cuda/fused_adam_cuda.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=fused_adam_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140,
                     from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /private/home/lucaspc/repos/fairscale/fairscale/clib/fused_adam_cuda/fused_adam_cuda.cpp:1:
    /tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
       83 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
        env=env)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/home/lucaspc/repos/fairscale/setup.py", line 80, in <module>
        "Operating System :: OS Independent",
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
        build_ext.build_extensions(self)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/private/home/lucaspc/.conda/envs/vissl/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/tmp/pip-build-env-sph0k8os/overlay/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /private/home/lucaspc/.conda/envs/vissl/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/home/lucaspc/repos/fairscale/setup.py'"'"'; __file__='"'"'/private/home/lucaspc/repos/fairscale/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output

```

**Comment by timothybrooks** [comment]
Which version of pytorch are you using? Could this possibly be related to the 1.8 release?

**Comment by pclucas14** [comment]
I tried with 2 environments, one with pytorch `'1.7.1+cu101'` and another one with a fresh out the box(so no pytorch yet). 
Right now I have just copy pasted the `fairscale` folder from another python 3.7 environment, which seems to do the job

**Comment by min-xu-ai** [comment]
without a repro, not much can be done. given we will likely avoid doing cpp compile in pip install, this shouldn't be an issue once that's done. closing.

**Comment by pclucas14** [comment]
Hi, 

I need to upgrade my fairscale so my previous solution does not work anymore. What do you need on my end to solve this ?

**Comment by pclucas14** [comment]
Actually this was only because I had loaded cuda 10.1 instead of 11. Worked after that

**Comment by Adrien987k** [comment]
> Actually this was only because I had loaded cuda 10.1 instead of 11. Worked after that

Hi,
I am facing the same issue. What do you mean by "I had loaded cuda 10.1" and what did you do to load cuda 11 ? 
Thanks.

**Comment by marload** [comment]
I have a same issue
