### ISSUE TITLE
[FSDP] SIGSEGV likely due to convert to sync_bn

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#489]
Happy on a regnet model but probably will need some repro error in other envs.

```
[149751.598999] /usr/local/fbco[3364576]: segfault at 0 ip 00007f8b452665df sp 00007ffc6bacce80 error 6 in libcaffe2_aten_cpukernel_avx2.so[7f8b44e9c000+498000]
```

```
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/fbcode/platform007/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/run_distributed_engines.py", line 58, in <module>
    hydra_main(overrides=overrides)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/run_distributed_engines.py", line 45, in hydra_main
    hook_generator=default_hook_generator,
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/utils/distributed_launcher.py", line 122, in launch_distributed
    daemon=False,
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGSEGV
```

Filing for the future. For now, will move on with workaround.

**Comment by min-xu-ai** [comment]
Likely this is not CPU specific. It looks like sync-bn conversion related:

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/utils/distributed_launcher.py", line 177, in _distributed_worker
    process_main(cfg, dist_run_id, local_rank=local_rank, node_id=node_id)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/utils/distributed_launcher.py", line 170, in process_main
    hook_generator=hook_generator,
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/engines/train.py", line 102, in train_main
    trainer.train()
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/trainer/trainer_main.py", line 155, in train
    self.task.prepare(pin_memory=self.cfg.DATA.PIN_MEMORY)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/trainer/train_task.py", line 643, in prepare
    self.base_model = self._build_model()
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/trainer/train_task.py", line 439, in _build_model
    model = convert_sync_bn(self.config, model)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/models/model_helpers.py", line 186, in convert_sync_bn
    ](group_size)
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/vissl/models/model_helpers.py", line 179, in to_pytorch_syncbn
    model, process_group=process_group
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/nn/modules/batchnorm.py", line 730, in convert_sync_batchnorm
    module_output.add_module(name, cls.convert_sync_batchnorm(child, process_group))
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/nn/modules/batchnorm.py", line 730, in convert_sync_batchnorm
    module_output.add_module(name, cls.convert_sync_batchnorm(child, process_group))
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/nn/modules/batchnorm.py", line 730, in convert_sync_batchnorm
    module_output.add_module(name, cls.convert_sync_batchnorm(child, process_group))
  [Previous line repeated 4 more times]
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/nn/modules/batchnorm.py", line 722, in convert_sync_batchnorm
    module_output.weight = module.weight
  File "/data/users/m1n/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/ssl_framework/tools/run_distributed_engines#link-tree/torch/nn/modules/module.py", line 970, in __setattr__
    .format(torch.typename(value), name))
TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
```

file here for more investigation.

**Comment by min-xu-ai** [comment]
We now do BN differently due to its need for full precision. This no longer is an issue.
