### ISSUE TITLE
test_column_paralle test assert on A100

### ISSUE THREAD

**Issue by elevenxiang** [facebookresearch/fairscale#810]
Hi, 

After install the fairscale, I try to run the example test as below:

pytest tests/nn/model_parallel/test_layers.py -s -rA -k  test_column_paralle

And then met the assert error, is this normal ? is it dependent on Hardware ?

tests/nn/model_parallel/test_layers.py::test_column_parallel dist init r=0, world=2
dist init r=1, world=2
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
> testing ColumnParallelLinear with model parallel size: 2
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 15063 and data parallel seed: 12345
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
   **error in dLdA on global rank 1: 0.0007064342498779297
   error in dLdA on global rank 0: 0.0008176565170288086**
**FAILED**

E       torch.multiprocessing.spawn.ProcessRaisedException:
E
E       -- Process 1 terminated with the following error:
E       Traceback (most recent call last):
E         File "/aisw/xiangzhi.xyc/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
E           fn(i, *args)
E         File "/aisw/xiangzhi.xyc/githubs/fairscale/tests/nn/model_parallel/test_layers.py", line 220, in run_test_column_parallel_linear
E           **assert error < 1.0e-6**
E       **AssertionError**

Thanks

**Comment by elevenxiang** [comment]
BTW, how to run test_row_parallel ?

Can I remove the "@pytest.mark.skipif("OMPI_COMM_WORLD_RANK" not in os.environ, reason="only works on mpi")" to run it ? or I have to must use mpirun to trigger it ?

mpirun -n 2 -mca orte_base_help_aggregate 0 python -m pytest tests/nn/model_parallel/test_layers.py -s -rA -k  test_row_parallel
