### ISSUE TITLE
FSDP crashes when saving optimizer state

### ISSUE THREAD

**Issue by butsugiri** [facebookresearch/fairscale#883]
Hi, thank you for the great library.

## Problem

I am currently trying to train Transformer Encoder-Decoder model with FSDP setup.
However, the program crashes in the middle of saving optimizer parameters.

This problem only occurs when I try to train a large model (e.g. 24 layers).
Setting the number of layers to 1 seems to be working OK.

## Error

```
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/code/fairseq/fairseq_cli/train.py", line 507, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/code/fairseq/fairseq/distributed/utils.py", line 344, in call_main
    torch.multiprocessing.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
​
-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/code/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/code/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/code/fairseq/fairseq_cli/train.py", line 305, in train
    valid_losses, should_stop = validate_and_save(
  File "/code/fairseq/fairseq_cli/train.py", line 398, in validate_and_save
    checkpoint_utils.save_checkpoint(
  File "/code/fairseq/fairseq/checkpoint_utils.py", line 49, in save_checkpoint
    trainer.consolidate_optimizer()  # TODO(SS): do we need this if no_save_optimizer_state
  File "/code/fairseq/fairseq/trainer.py", line 376, in consolidate_optimizer
    st = self.model.gather_full_optim_state_dict(
  File "/opt/conda/lib/python3.8/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 2230, in gather_full_optim_state_dict
    state, singleton_state = self._gather_optim_state(sd.pop("state"))
  File "/opt/conda/lib/python3.8/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 2174, in _gather_optim_state
    assert (
AssertionError: Only flatten param or a single non-shared param is supported: len=0
​
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 480 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

## Environment

- PyTorch:  1.10.0a0+ecc3718
- Fairseq: https://github.com/pytorch/fairseq/commit/bf61974ee879cb1a5b188440ddb06a2f43a8fef9
- Fairscale: 0.4.3
- Hardware: Nvidia A100 x4

## Command
```shell
fairseq-train \
    ${DATASET} \
    --save-dir ${SAVE_DIR} \
    --arch transformer \
    --encoder-attention-heads 32 \
    --decoder-attention-heads 32 \
    --decoder-output-dim 1024 \
    --encoder-embed-dim 1024 \
    --decoder-embed-dim 1024 \
    --encoder-ffn-embed-dim 8192 \
    --decoder-ffn-embed-dim 8192 \
    --encoder-layers 24 \
    --decoder-layers 24 \
    --encoder-normalize-before \
    --decoder-normalize-before \
    --share-decoder-input-output-embed \
    --lr 0.001 \
    --max-tokens 16000 \
    --update-freq 1 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 0.001 --lr-scheduler inverse_sqrt --warmup-updates 8000 \
    --dropout 0.1 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --ddp-backend fully_sharded \
    --max-update 10 \
    --keep-last-epochs 5 \
    --num-workers 32 \
    --checkpoint-activations \
    --no-save-optimizer-state \
    --log-interval 1 2>&1 | tee ${SAVE_DIR}/log.without.ckpt.batch16k.txt
```

**Comment by min-xu-ai** [comment]
This is strange. I remember that fairseq uses flatten_parameters=True already. @dianaml0, do you happen to know what might be happening?

**Comment by Cattacker** [comment]
这是来自QQ邮箱的假期自动回复邮件。我已收到您的邮件。

**Comment by min-xu-ai** [comment]
OK, I think not much is going to happen here. Feel free to reopen. Best way forward is perhaps to try a different and newer fairseq version.
