### ISSUE TITLE
message.tensors[0] error

### ISSUE THREAD

**Issue by guozhiyao** [facebookresearch/fairscale#895]
I want to use the `PipeRPCWrapper` to do the PP in multi-process. I follow the `tests/nn/pipe_process/test_rpc.py` and my code as follow
```
import fairscale
import fairscale.nn.model_parallel as mp

init_rpc()
mp.initialize_model_parallel(model_parallel_size_=1, pipeline_length=2)
if dist.get_rank()!=0:
  rpc.shutdown()
  exit()
net = get_model()
net = fairscale.nn.pipe.PipeRPCWrapper(net, balance, input_device=torch.cuda.current_device(), worker_map={rank: f"Worker{rank}" for rank in range(dist.get_world_size())})
for batch in data_iter:
  output = net(input)
```
and the error shows that
```
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fairscale/nn/pipe/rpc.py", line 183, in forward
    result = self._recv_result(self.model, shape, dtype, activations)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fairscale/nn/pipe/rpc.py", line 214, in _recv_result
    return message.tensors[0]
IndexError: tuple index out of range
On WorkerInfo(id=1, name=Worker1):
RuntimeError('got 1 tensors and 0 gradients')
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/distributed/rpc/internal.py", line 190, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fairscale/nn/pipe/rpc.py", line 242, in _send_result_and_do_backwards
    torch.autograd.backward(result, grads_message.tensors, retain_graph=True)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: got 1 tensors and 0 gradients
```

**Comment by min-xu-ai** [comment]
Thanks for the report. Is this still a problem after you have found the bug in #898?

Unfortunately, we no longer have the expert on MP pipe within the FB team. If you have time to fix it up, it would be great. Otherwise, I am afraid that this won't be fixed any time soon.

**Comment by guozhiyao** [comment]
> Thanks for the report. Is this still a problem after you have found the bug in #898?
> 
> Unfortunately, we no longer have the expert on MP pipe within the FB team. If you have time to fix it up, it would be great. Otherwise, I am afraid that this won't be fixed any time soon.

This is the problem raised by the bug.
