### ISSUE TITLE
mypy not running?

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#915]
On top of main, it seems that mypy is not clean. Can you guys see the same errors? @anupambhatnagar @anj-s @tmarkstrum 

```
fairscale/utils/parallel.py:107: error: Incompatible return value type (got "None", expected "ProcessGroup")
                return None
                       ^
fairscale/optim/adascale.py:538: error: unused "type: ignore" comment
                self._state[name] = np.append(self._state[name], val)  # type: ignore
                ^
tests/optim/test_layerwise_gradient_scaler.py:73: error: Incompatible return value type (got "Optional[Tuple[Any, Any]]", expected "Union[DataLoader[Any], Tuple[Any, Any]]")
        return data
               ^
fairscale/optim/grad_scaler.py:93: error: Call to untyped function "amp_definitely_not_available" in typed context
            if enabled and amp_definitely_not_available():
                           ^
fairscale/optim/grad_scaler.py:368: error: Item "None" of "Optional[Tensor]" has no attribute "fill_"
                    self._scale.fill_(new_scale)
                    ^
fairscale/optim/grad_scaler.py:374: error: Item "None" of "Optional[Tensor]" has no attribute "copy_"
                    self._scale.copy_(new_scale)
                    ^
fairscale/nn/pipe/async_schedule.py:282: error: Item "None" of "Optional[Any]" has no attribute "grad_from_pipeline"
            batch.tensor.grad_fn.grad_from_pipeline = tuple(recvd_grads.tensors)
            ^
fairscale/experimental/nn/ampnet_pipe/pipe.py:49: error: Item "None" of "Optional[AsyncPipeline]" has no attribute "transport"
            transport = self.pipeline.transport
                        ^
fairscale/experimental/nn/ampnet_pipe/pipe.py:50: error: Item "None" of "Optional[AsyncPipeline]" has no attribute "checkpoint_stop"
            checkpoint_stop = self.pipeline.checkpoint_stop
                              ^
fairscale/optim/oss.py:295: error: Item "None" of "Optional[Tensor]" has no attribute "detach"
                            p.grad.detach().mul_(clip_coef.to(device))
                            ^
fairscale/nn/data_parallel/fully_sharded_data_parallel.py:397: error: Item "None" of "Optional[OffloadConfig]" has no attribute "offload_type"
                raise ValueError(f"offload type: '{offload_config.offload_type}' requires flatten_parameters=True")
                                 ^
tests/nn/data_parallel/test_fsdp_hf_transformer_eval.py:45: error: Incompatible types in assignment (expression has type "None", variable has type "FloatTensor")
        output: torch.FloatTensor = None
                                    ^
Found 12 errors in 9 files (checked 292 source files)
```

**Comment by min-xu-ai** [comment]
With fresh pre-commit install (after removing its dir in $HOME/.cache), I still get errors on my home machine. But not on FB machines

```
- hook id: seed-isort-config
- exit code: 1

Traceback (most recent call last):
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/bin/seed-isort-config", line 8, in <module>
    sys.exit(main())
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/seed_isort_config.py", line 112, in main
    third_party = third_party_imports(filenames, appdirs)
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/seed_isort_config.py", line 60, in third_party_imports
    visitor.visit(ast.parse(f.read(), filename=filename))
  File "/8TB/work/miniconda3/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/8TB/work/miniconda3/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/8TB/work/miniconda3/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/seed_isort_config.py", line 48, in visit_ImportFrom
    self._maybe_append_name(node.module)
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/seed_isort_config.py", line 35, in _maybe_append_name
    imp_type = classify_import(name, self.appdirs)
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/aspy/refactor_imports/classify.py", line 138, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/home/owen/.cache/pre-commit/reporbf313e0/py_env-python3/lib/python3.9/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError

isort....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

fairscale/optim/adascale.py:538: error: unused "type: ignore" comment
                self._state[name] = np.append(self._state[name], val)  # t...
                ^
Found 1 error in 1 file (checked 226 source files)

```

**Comment by min-xu-ai** [comment]
closing since this is likely some kind of version issue between environments. The behavior of mypy is far from perfect.
