### ISSUE TITLE
FSDP fails with loss backward

### ISSUE THREAD

**Issue by LEECHOONGHO** [facebookresearch/fairscale#920]
When I try to use FSPD, I got an error in loss backward.
Has anyone experienced the same problem?
I'm still a beginner, so there may be a problem in the code stage.

**1. Error Message**
```
Traceback (most recent call last):
  File "xi_train.py", line 363, in <module>
    mp.spawn(
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/leecho/xi-tts-ml/xi_train.py", line 255, in train
    loss_dict['total_loss'].backward()
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/anaconda3/envs/xi-tts-ml/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
SystemError: <built-in method run_backward of torch._C._EngineBase object at 0x7f5406a98540> returned NULL without setting an error
```
**2. Code**
```
def train(
    rank,
    preprocess_config,
    model_config,
    train_config,
    train_df,
    state_data,
    speaker_id_dict,
):
    world_size = train_config['world_size']

    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.set_device(rank)
    dist.init_process_group(backend='nccl', init_method="tcp://localhost:29501", rank=rank, world_size=world_size)
    
    # Define Dataset & Collator
    xinapse_train_dataset = XinapseDataset(train_config, preprocess_config, train_df, speaker_id_dict)
    
    collator = PadCollate(train_config['seq_len_dim'], state_data)
    
    # Define Model
    with enable_wrap(
        wrapper_cls=FullyShardedDataParallel
    ):
        model = wrap(
            Xi_TTS(preprocess_config, model_config, train_config),
            process_group=torch.distributed.new_group(),
            reshard_after_forward=False,
            # mixed_precision=True,
            flatten_parameters=True,
            compute_dtype=torch.float32
        )
    
    # Define Loss Function & Optimizer
    loss_fn = Xi_TTS_Loss(preprocess_config, model_config, train_config).to(rank)

    optimizer = torch.optim.Adam(
        model.parameters(),
        betas=train_config["optimizer"]["betas"],
        eps=train_config["optimizer"]["eps"],
        weight_decay=train_config["optimizer"]["weight_decay"],
    )
    
    # Define Sampler & Data Loader
    train_sampler = DistributedSampler(xinapse_train_dataset, num_replicas=world_size, rank=rank, shuffle=True)

    train_dataloader = torch.utils.data.DataLoader(xinapse_train_dataset, batch_size=int(train_config['optimizer']['batch_size']/world_size), shuffle=(train_sampler is None),
                                         collate_fn=collator, pin_memory=True, sampler=train_sampler)

    model.train()
    
    training_step = 0
    keep_training = True

    while keep_training:
        
        for inputs in train_dataloader:
            
            inputs = {k : v.to(rank) for k, v in inputs.items()}
            # inputs = {k : v.to(rank).half() if v.type() == 'torch.FloatTensor' else v.to(rank) for k, v in inputs.items()}

            training_step += 1

            optimizer.zero_grad()
            
            predictions = model(inputs, training_step)
            
            loss_dict = loss_fn(inputs, predictions, training_step)

            loss_dict['total_loss'].backward()

            # Clipping gradients to avoid gradient explosion
            nn.utils.clip_grad_norm_(model.parameters(), train_config["optimizer"]["grad_clip_thresh"])

            _update_learning_rate(optimizer, training_step, train_config)
            optimizer.step()
            
            if rank == 0:
                logger('[Train ', train_config['train_log_name'], train_config['step']['log_step'], loss_dict, training_step)
                save_model(model, train_config['step']['save_step'], training_step, train_config)
                plot_output(predictions, inputs, training_step, train_config)

            if training_step == train_config['step']['total_step']:
                print('Training has ended.')
                keep_training = False
                dist.destroy_process_group()
                break

if __name__ == '__main__': 
   #... loading configs, df, dict
    mp.spawn(
        train,
        # trainer.train_sequence,
        args=(
            preprocess_config,
            model_config,
            train_config,
            train_df,
            state_data,
            speaker_id_dict,
        ),
        nprocs=min(torch.cuda.device_count(), train_config['world_size']),
        join=True,
    )
```

**3. Environment**
 Docker
 ubuntu 20.04
 cuda 11.5
 cudnn 8
 torch 1.10.1

**Comment by SparkJiao** [comment]
Hi, have your solved this problem?

**Comment by LEECHOONGHO** [comment]
@SparkJiao 
Hello, I use ShardedDDP instead of FSDP.
Maybe FSDP is not supporting multiple losses yet.
https://github.com/facebookresearch/fairscale/issues/918

**Comment by SparkJiao** [comment]
> @SparkJiao Hello, I use ShardedDDP instead of FSDP. Maybe FSDP is not supporting multiple losses yet. #918

I see. Thank you very much!

**Comment by xdd12135** [comment]
I get this problem too, and I just want to use FSDP ,how should I solve this problem?  I don't have multiple losses in my code.
